### ISSUE TITLE
update_all() fails when updating first non-root environment

### ISSUE THREAD

**Issue by joshvernon** [joshvernon/conda-scripts#6]
`update_all()` - called with the `update_root` argument set to `True` or `False` - will faill with the below exception when it gets to the first non-root enviroment:

```
Result from environment root:
{u'message': u'All requested packages already installed.', u'success': True}
Traceback (most recent call last):
  File "./local_updater.py", line 6, in <module>
    update_all(True, *blacklist_envs)
  File "/home/josh/codebase/python/temp/conda-scripts/conda_tools/updater.py", line 47, in update_all
    env_update_result = conda_api.update(env=env_name, all=True)
  File "/home/josh/miniconda2/lib/python2.7/site-packages/conda_api.py", line 270, in update
    raise CondaError('conda %s: %s' % (" ".join(cmd_list), result['error']))
conda_api.CondaError: conda update --json --quiet --yes --name miniconda2 --all: EnvironmentLocationNotFound: Not a conda environment: /home/josh/miniconda2/envs/miniconda2
```

**Comment by joshvernon** [comment]
The root cause of the issue is that conda now prepends the root environment to the list of envs returned in `conda info --json` (where `conda_api.get_envs()` gets its environments from). The below is the `envs` object returned in the `conda info --json` response:

"envs": [
    **"/home/josh/miniconda2",**
    "/home/josh/miniconda2/envs/arcgis-python-api",
    "/home/josh/miniconda2/envs/curio",
    "/home/josh/miniconda2/envs/flask-dev",
    "/home/josh/miniconda2/envs/mq",
    "/home/josh/miniconda2/envs/tk",
    "/home/josh/miniconda2/envs/websocket"
  ]

The fix was to slice to the list comprehension to exclude the first element.
